name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  published-to-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger autobump workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run autobump.yml \
            --repo kszakharov/homebrew-tap \
            -f formulae="${{ github.event.repository.name }}"
