name: Trigger upstream autobump

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger autobump workflow
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run autobump.yml \
            --repo kszakharov/homebrew-tap \
            -f formulae=rada
