name: Create GitHub Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
#ralphex_1.0.1_checksums.txt
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TZ: America/Toronto
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/workflows/build.yml

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rada-${GITHUB_REF_NAME#v}.tar.gz
          path: dist
      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          sed -n "/^## \[${{ steps.vars.outputs.version }}\]/,/^## \[/p"  CHANGELOG.md | sed '1d; :a; /^[[:space:]]*$/ {N; ba}; $ { /^[[:space:]]*$/d }' > RELEASE_NOTES.md

          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.release_notes }}
          files: dist/*
          generate_release_notes: false
